language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
install:
- pip install -r requirements.txt
script:
- make clean
- make html
env:
  global:
  - secure: vqlucGMzLPv4hPX3cXbcrQ+cI/rgCHNZ/rfb53MGWVhCpoQs6fspS9TFtjM/P/LD66N2TpmzGSiRE9O4IMg2DP/QCWqSHBu33vMpMbkac8PsWuBoS1HktxhrkfPKMQ5J7p8fnbmAZGLsIuzB3Bmrnic3edjWUeXtUMu8O6cHjToR2pTX0dxuX2HLiJH0HFGgf5rERmBn7DBTa0Q75vshVB4uPI8ObWMemphNspRSHcCgQUoMTnBt/1u0irY6W1AvBfvo2rrNs4PKAJZsBB2l57LYPeeLFqKgEAvVVN149mgi8YfJ687LfVV5OHfeyZb8aMF3uyqrzFn7DoObJ3M7FvL78UfQljuupd/iwJIYxVt7zPnc33BO6+qoFBDLDWmQwsr+yPs4aIVksPS4+MEPZIt6p4IFtzcbdZwyWHiRiGrl7VznsgFQHeWUWFQ/czTI8P0zqdHk6Y0FpDtDyaGort8Kjh16XLTxJEV88lVRB9MLrceZGEfsnhTsi7YBCzjqX2/HW1k5iQ8+BKou+d1ccgRm+BS2ES6Cio5DXbMPqqbPX+JlpavnNM4dlHMSyFeUuGyMur5UBlTNQB5X8zxROS5/pDpxmKMoUW80u4WD258TNcN7A9GVRfKLNhtoBmYRZeLOnkYsLVmMJhEDpuGtsMHGGIXg7iwOG7w+Y029XIE=
after_success:
- bash deploy.sh
