language: python
python:
- '2.7'
before_install:
- sudo apt-get update -qq
- sudo apt-get install openssl --no-install-recommends -y --force-yes
- openssl aes-256-cbc -K $encrypted_281f99f6d69c_key -iv $encrypted_281f99f6d69c_iv
  -in gh_pages.pub.enc -out id_rsa.pub -d
install:
- pip install -r requirements.txt
script: bash deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: 281f99f6d69c
  - COMMIT_AUTHOR_EMAIL: babuenir@gmail.com
